sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - if [ $TRAVIS_PHP_VERSION != "7.0" ] && [ $TRAVIS_PHP_VERSION != "7.2" ]; then phpenv config-rm xdebug.ini; fi

script:
  - if [ $TRAVIS_PHP_VERSION == "7.0" ]; then make test-coveralls; else make test; fi
